---
- hosts: kslave1
  become: yes
  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
 
    - name: Install Python3 package
      apt:
        name: python3
        state: present
    - name: Install git package
      apt:
        name: git
        state: present
    - name: Install open-ssh package
      apt:
        name: openssh-server
        state: present
